	SUBROUTINE DFEXS(I,IR,NR,RHO,DFS)

	IMPLICIT NONE

      REAL*8 RHOB,DC,DP,T,MIX_F,RB,RC,DR,TOLE,PI
      COMMON RHOB,DC,DP,T,MIX_F,RB,RC,DR,TOLE,PI

      INTEGER NP,I,K,IR,IP
      PARAMETER(NP=2**13)
	INTEGER NR
	REAL*8 RHO(NP)
	REAL*8 RE1TEM
	REAL*8 DFS,MUSB

	REAL*8 R,R1,R12,del,temp
	INTEGER KIN,KIP

! Shifted potential in the bulk
	MUSB=-16.*PI*RHOB*DP**3*((DP/RC)**9-(DP/RC)**3)/(3.*T)

! LJ Potenial/2 at RC
	TEMP=2.*((DP/RC)**12-(DP/RC)**6) 

	R=DC/2+FLOAT(I-1)*DR

! INTEGRATION UP TO THE CALCULATION BOUNDARY NR
	KIN=NINT(DP/2./DR)+1 ! THE FIRST NON-ZERO DENSITY POINT
	KIP=NR

	DFS=0.0

	DO K=KIN,KIP

	R1=DC/2+FLOAT(K-1)*DR

	DEL=ABS(R1-R)
	R12=R+R1

	IP=K-IR+1	 !INDEX FOR THE DENSITY PROFILE

	IF (DEL.GE.RC) THEN

	RE1TEM=0.

	ELSEIF (R12.LE.RC) THEN
	RE1TEM=-TEMP*(R12**2-DEL**2)

	ELSE
	RE1TEM=-TEMP*(RC**2-DEL**2)
	ENDIF

	IF ((K.EQ.KIN).OR.(K.EQ.KIP)) THEN
	DFS=DFS+(RHO(IP)-RHOB)*R1*RE1TEM/2.
	ELSE
	DFS=DFS+(RHO(IP)-RHOB)*R1*RE1TEM
	ENDIF

	ENDDO

	DFS=DFS*DR*2.*PI/R/T

	DFS=MUSB+DFS

	RETURN
	END

